require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://github.com/Banuba/specs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
inhibit_all_warnings!

platform :ios, '13.0'
install! 'cocoapods', :deterministic_uuids => false

production = ENV["PRODUCTION"] == "1"

target 'vesdkreactnativecliintegrationsample' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :production => production,
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
#     :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

    sdk_version = '1.29.2'

    pod 'BanubaARCloudSDK', sdk_version #optional
    pod 'BanubaVideoEditorSDK', sdk_version
    pod 'BanubaAudioBrowserSDK', sdk_version #optional
    pod 'BanubaSDKSimple', sdk_version
    pod 'BanubaEffectPlayer', sdk_version
    pod 'BanubaSDK', sdk_version
    pod 'BanubaSDKServicing', sdk_version
    pod 'VideoEditor', sdk_version
    pod 'BanubaUtilities', sdk_version
    pod 'BanubaVideoEditorGallerySDK', sdk_version #optional
    pod 'BanubaLicenseServicingSDK', sdk_version

    pod 'BNBLicenseUtils', sdk_version

    pod 'VEExportSDK', sdk_version
    pod 'VEEffectsSDK', sdk_version
    pod 'VEPlaybackSDK', sdk_version

  target 'vesdkreactnativecliintegrationsampleTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
