# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

source 'https://github.com/Banuba/specs.git'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/sdk-banuba/banuba-sdk-podspecs.git'
inhibit_all_warnings!

platform :ios, '15.0'
prepare_react_native_project!

production = ENV["PRODUCTION"] == "1"

target 'vesdkreactnativecliintegrationsample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :production => production,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

    sdk_version = '1.37.0'

    # Video Editor
    pod 'BanubaARCloudSDK', sdk_version #optional
    pod 'BanubaVideoEditorSDK', sdk_version
    pod 'BanubaAudioBrowserSDK', sdk_version #optional
    pod 'BanubaSDKSimple', sdk_version
    pod 'BanubaSDK', sdk_version
    pod 'BanubaSDKServicing', sdk_version
    pod 'VideoEditor', sdk_version
    pod 'BanubaUtilities', sdk_version
    pod 'BanubaVideoEditorGallerySDK', sdk_version #optional
    pod 'BanubaLicenseServicingSDK', sdk_version

    pod 'BNBLicenseUtils', sdk_version

    pod 'VEExportSDK', sdk_version
    pod 'VEEffectsSDK', sdk_version
    pod 'VEPlaybackSDK', sdk_version

    # Photo Editor
    pod 'BanubaPhotoEditorSDK', '1.2.3'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end
end
